# https://taskfile.dev
version: '3'

dotenv: ["env"]

env:
  GOOSE_DRIVER: postgres
  GOOSE_MIGRATION_DIR: db/migrations

vars:
  CONNSTRING: postgresql://postgres:$POSTGRES_PASSWORD@localhost:5432/musiclisteners

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
     
# === Application Tasks ===
  app-seed:
    dir: src/
    cmds:
      - go run cmd/seed/main.go

  app-run:
    dir: src/
    cmds:
      - go run cmd/app/main.go


# === Docker Tasks ===
  build-project:
    cmds:
      - docker compose -p project -f docker/docker-compose.yaml build

  deploy-project:
    cmds:
      - docker compose -p project -f docker/docker-compose.yaml build
      - docker compose -p project -f docker/docker-compose.yaml up -d

  destroy-project:
    cmds:
      - docker compose -p project -f docker/docker-compose.yaml down

  ps:
    cmds:
      - docker compose -p project -f docker/docker-compose.yaml ps

  restart-project:
    cmds:
      - task destroy-project
      - task deploy-project


# === Migration Tasks ===
  migration-status:
    cmds:
      - GOOSE_DBSTRING={{.CONNSTRING}} goose status 

  migration-version:
    cmds:
      - GOOSE_DBSTRING={{.CONNSTRING}} goose version

  migration-new:
    cmds:
      - GOOSE_DBSTRING={{.CONNSTRING}} goose create {{.CLI_ARGS}} sql


  migration-up:
    cmds:
      - APP_USER_POSTGRES_PASSWORD=$APP_USER_POSTGRES_PASSWORD GOOSE_DBSTRING={{.CONNSTRING}} goose up

  migration-down:
    cmds:
      - APP_USER_POSTGRES_PASSWORD=$APP_USER_POSTGRES_PASSWORD GOOSE_DBSTRING={{.CONNSTRING}} goose down
