services:
  db:
    container_name: database
    image: postgres:16
    env_file: ../env
    ports:
    - "5432:5432"
    volumes:
    - "$PWD/db/initdb/01_create_database.sh:/docker-entrypoint-initdb.d/01.sh"
