-- +goose Up
-- +goose StatementBegin
-- +goose ENVSUB ON
GRANT ALL PRIVILEGES ON DATABASE musiclisteners TO ${APP_USER_POSTGRES_USERNAME};
GRANT USAGE on SCHEMA production TO ${APP_USER_POSTGRES_USERNAME};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA production TO ${APP_USER_POSTGRES_USERNAME};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA production TO ${APP_USER_POSTGRES_USERNAME};
-- +goose ENVSUB OFF
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose ENVSUB ON
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA production FROM ${APP_USER_POSTGRES_USERNAME};
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA production FROM ${APP_USER_POSTGRES_USERNAME};
REVOKE USAGE ON SCHEMA production FROM ${APP_USER_POSTGRES_USERNAME};
REVOKE ALL PRIVILEGES ON DATABASE musiclisteners FROM ${APP_USER_POSTGRES_USERNAME};
-- +goose ENVSUB OFF
-- +goose StatementEnd
